<?php
require __DIR__ . '/includes/config.php';
require __DIR__ . '/components/icons.php';
require __DIR__ . '/components/header.php';
?>
<main id="main" tabindex="-1">
    <section class="hero" id="product">
        <div class="container hero-layout"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> FLEET MANAGEMENT SOFTWARE FOR UK BUSINESSES</p><h1><span class="hero-brand">FleetIQ</span>Smarter Fleet<br><span class="gradient-text">Management.</span></h1><p class="hero-lead">One system for your vehicles, drivers, compliance, documents and workshop.</p><p class="hero-secondary">Manage your fleet from Windows, Web and Android.</p><div class="hero-actions"><a class="button" href="contact.php">Book a Demo <?php icon('arrow'); ?></a><a class="button button-outline" href="#features">Explore FleetIQ <?php icon('arrow'); ?></a></div><div class="hero-platforms"><span><?php icon('desktop'); ?> Windows</span><span><?php icon('globe'); ?> Web</span><span><?php icon('phone'); ?> Android</span><i></i><span>One connected fleet.</span></div></div><div class="hero-product">
            <?php require __DIR__ . '/components/dashboard.php'; ?>
            <div class="hero-phone" role="img" aria-label="Conceptual Android daily inspection with three of eight checks complete">
                <span class="phone-speaker" aria-hidden="true"></span>
                <?php brand(); ?>
                <p class="phone-kicker">ANDROID &middot; DAILY CHECK</p>
                <strong>FQ26 ABC</strong>
                <span class="phone-subtitle">Ford Transit</span>
                <div class="phone-check"><?php icon('check'); ?> Lights & indicators</div>
                <div class="phone-check"><?php icon('check'); ?> Tyres & wheels</div>
                <div class="phone-check"><?php icon('check'); ?> Mirrors & glass</div>
                <div class="phone-progress">3 of 8 checks complete</div>
            </div>
            <p class="visual-caption">Conceptual product views &middot; Illustrative data</p>
        </div></div>
        <ul class="container hero-feature-strip" aria-label="FleetIQ capabilities">
            <li><?php icon('vehicle'); ?> Vehicles</li>
            <li><?php icon('users'); ?> Drivers</li>
            <li><?php icon('shield'); ?> Compliance</li>
            <li><?php icon('calendar'); ?> Calendar</li>
            <li><?php icon('document'); ?> Documents</li>
            <li><?php icon('tool'); ?> Workshop</li>
        </ul>
    </section>
    <div class="sector-strip"><div class="container"><span>Built for fleets.<br><b>Designed for the real world.</b></span><p>Transport & haulage</p><p>Construction & plant</p><p>Service & courier fleets</p><p>Taxi & passenger transport</p></div></div>
    <section class="section benefits" id="about"><div class="container"><div class="section-heading"><div><p class="eyebrow">LESS ADMIN. MORE OVERSIGHT.</p><h2>Keep your fleet moving</h2></div><p>When fleet, driver and workshop responsibilities overlap, it helps to have everything in one place.</p></div><div class="benefit-grid">
    <?php foreach ([['calendar', 'Never miss an important date', 'Keep upcoming MOTs, services and renewals in view, so you can plan ahead.'], ['shield', 'Keep compliance visible', 'See the status of vehicle and driver requirements in one organised workspace.'], ['tool', 'Manage defects through to repair', 'Connect reported defects to repair jobs and keep a clear record of the work.'], ['document', 'Centralise documents', 'Keep certificates, licences and vehicle records alongside the people and vehicles they belong to.'], ['inspection', 'Run inspections digitally', 'Give drivers a consistent way to complete checks and record defects on Android.'], ['chart', 'See what needs attention', 'Bring due dates, outstanding work and recent activity into a clear fleet overview.']] as [$symbol, $title, $copy]): ?>
        <article class="benefit-card"><div class="icon-box"><?php icon($symbol); ?></div><h3><?= $title ?></h3><p><?= $copy ?></p></article>
    <?php endforeach; ?></div></div></section>
    <section class="section features" id="features"><div class="container"><div class="center-heading"><p class="eyebrow">YOUR EVERYDAY WORK. ALL CONNECTED.</p><h2>Powerful features. Practical benefits.</h2><p>From daily checks to the bigger picture, give every part of your fleet a place.</p></div><div class="feature-grid">
    <?php foreach ([['vehicle', 'Vehicles', 'The complete vehicle record'], ['users', 'Drivers', 'People, licences and records'], ['shield', 'Compliance', 'Requirements in clear view'], ['calendar', 'Calendar', 'Plan the work ahead'], ['document', 'Documents', 'Everything in its place'], ['tool', 'Workshop', 'Keep jobs moving'], ['inspection', 'Inspections', 'Consistent digital checks'], ['check', 'Repairs', 'From defect to completion'], ['chart', 'Reports', 'A clearer view of your fleet'], ['lock', 'User permissions', 'The right access for each role']] as [$symbol, $title, $copy]): ?>
        <article class="feature-card"><?php icon($symbol); ?><h3><?= $title ?></h3><p><?= $copy ?></p></article>
    <?php endforeach; ?></div></div></section>
    <section class="section intelligence dark-section" id="reports"><div class="container intelligence-layout"><div><p class="eyebrow">A CLEARER PICTURE</p><h2>Know what needs attention.</h2><p>Start with the information that matters. FleetIQ brings important dates, outstanding defects and workshop activity together, so you can focus on the next job.</p><ul class="check-list"><li><?php icon('check'); ?> Due soon and overdue dates</li><li><?php icon('check'); ?> Vehicle and driver compliance status</li><li><?php icon('check'); ?> Workshop attention and open defects</li><li><?php icon('check'); ?> Recent activity across your fleet</li></ul><a class="text-link" href="#compliance">Bring your fleet into focus <?php icon('arrow'); ?></a></div><div class="attention-visual"><div class="attention-head"><span><?php icon('grid'); ?> Attention centre</span><span class="badge blue">Fleet overview</span></div><h3>Ahead of the next deadline.</h3><p>Your priorities, in one place.</p><div class="attention-row"><span class="attention-icon amber"><?php icon('calendar'); ?></span><div><b>8 items due soon</b><small>Plan ahead for the next 30 days</small></div><span class="attention-number amber">08</span></div><div class="attention-row"><span class="attention-icon red"><?php icon('bell'); ?></span><div><b>3 overdue requirements</b><small>Review outstanding dates</small></div><span class="attention-number red">03</span></div><div class="attention-row"><span class="attention-icon blue"><?php icon('tool'); ?></span><div><b>5 workshop jobs open</b><small>Keep repairs moving towards completion</small></div><span class="attention-number blue">05</span></div><div class="attention-row"><span class="attention-icon red"><?php icon('tool'); ?></span><div><b>2 defects awaiting repair</b><small>Review and assign the next action</small></div><span class="attention-number red">02</span></div>
<div class="compliance-summary"><?php icon('shield'); ?><span><b>Compliance status</b><small>3 overdue requirements to review</small></span><span class="badge amber">Action needed</span></div>
<div class="activity-line"><span class="status-dot"></span> Recent activity <span>Inspection completed · FQ26 ABC</span></div><p class="visual-caption">Conceptual view · Illustrative data</p></div></div></section>
    <section class="section compliance" id="compliance"><div class="container compliance-layout"><div><p class="eyebrow">STAY A STEP AHEAD</p><h2>Compliance made simple</h2><p>Keep the dates and documents that matter to your operation together. Make renewals easier to plan and outstanding requirements easier to spot.</p><div class="guidance"><?php icon('shield'); ?><span>Informed by published DVSA guidance</span></div><p class="small-copy">Requirements differ between organisations, vehicle types and driver roles. Track the requirements relevant to your fleet; not every item applies to every operation.</p></div><div class="compliance-grid"><?php foreach (['MOT', 'Service', 'Driving Licence', 'CPC', 'Medical', 'DBS', 'Taxi Licence', 'Taxi Plate', 'Document Expiry'] as $label): ?><div><?php icon('check'); ?><span><?= $label ?></span></div><?php endforeach; ?></div></div></section>
    <section class="section workshop" id="workshop"><div class="container"><div class="center-heading"><p class="eyebrow">FROM CHECK TO COMPLETION</p><h2>Workshop management<br>that keeps you in control</h2><p>A connected process for the people doing the checks and the people doing the repairs.</p></div><ol class="workflow"><?php foreach ([['inspection', 'Inspection', 'Start with a digital check'], ['bell', 'Defect', 'Record what needs work'], ['tool', 'Repair Job', 'Organise the repair'], ['check', 'Completion', 'Record the outcome'], ['chart', 'History / Reporting', 'Keep a traceable record']] as $index => [$symbol, $title, $copy]): ?><li><div class="workflow-icon"><?php icon($symbol); ?><span><?= $index + 1 ?></span></div><h3><?= $title ?></h3><p><?= $copy ?></p></li><?php endforeach; ?></ol><div class="workshop-tags"><span>Digital inspections</span><span>Inspection templates</span><span>Defect management</span><span>Repair jobs</span><span>Inspection history</span><span>Workshop reporting</span></div></div></section>
    <section class="section devices dark-section" id="mobile"><div class="container devices-layout"><div class="device-visual" role="img" aria-label="Conceptual Windows desktop, Web browser and Android views sharing fleet records"><div class="mini-desktop"><div class="device-title"><?php brand(); ?><span>Windows &middot; Fleet overview</span></div><div class="mini-screen"><div class="mini-rail"><?php icon('grid'); ?><?php icon('vehicle'); ?><?php icon('users'); ?><?php icon('tool'); ?></div><div class="mini-data"><b>Your fleet at a glance</b><div class="mini-stats"><span>Vehicles<strong>48</strong></span><span>Due soon<strong>8</strong></span><span>Workshop<strong>5</strong></span></div><div class="mini-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><small>Fleet activity · Illustrative data</small></div></div></div><div class="desktop-stand"></div>
<div class="web-preview"><div class="web-toolbar"><span aria-hidden="true">? &middot; ?</span> Web &middot; FleetIQ</div><div class="web-record"><?php icon('vehicle'); ?><span><b>FQ26 ABC</b><small>Vehicle record &middot; MOT due 18 Sep</small></span><span class="badge amber">Due soon</span></div></div><div class="mini-phone"><div class="phone-speaker"></div><?php brand(); ?><p>Vehicle inspection</p><b>FQ26 ABC</b><small>Daily vehicle check</small><div class="phone-check"><?php icon('check'); ?> Lights & indicators</div><div class="phone-check"><?php icon('check'); ?> Tyres & wheels</div><div class="phone-check"><?php icon('check'); ?> Mirrors & glass</div><div class="phone-progress">3 of 8 checks complete</div></div><p class="visual-caption">Conceptual device views · Illustrative data</p></div><div><p class="eyebrow">IN THE OFFICE. OUT ON THE ROAD.</p><h2>One fleet.<br>One system.<br><span>One source of truth.</span></h2><p>Bring office, driver and workshop teams together with Windows, Web and Android, connected to one central shared database.</p><div class="device-platforms"><span><?php icon('desktop'); ?>Windows</span><span><?php icon('globe'); ?>Web</span><span><?php icon('phone'); ?>Android</span></div><p class="small-copy">The same fleet information, wherever the work takes you.</p></div></div></section>
    <?php require __DIR__ . '/components/demo-cta.php'; ?>
</main>
<?php require __DIR__ . '/components/footer.php'; ?>
